name: ML CI/CD pipeline
on: [push]
jobs:
  train:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python src/pipes/trainer.py
          
          echo "## Model Metrics" > report.md
          cat reports/results/metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish reports/figures/model_results.png --md >> report.md
          
          cml-send-comment report.md
    
  doc:
    needs: train
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: 'Generate docs'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install ghp-import
          cd src
          sphinx-apidoc -o ../docs .
          cd ..
          make -C docs clean 
          make -C docs html
          ghp-import -n -p -f docs/_build/html
  
  docker:
    needs: train
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy docker
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web